using System;
using System.Collections.Generic;
using UnityEngine;

// Legacy click structure (kept for reference but no longer used except for MemoryGame-specific clicks)
[Serializable]
public class ClickEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public string scene;
    public string area;
    public string target;
    public string inputType;
    public float x;
    public float y;
}

[Serializable]
public class OutcomeEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public float timeSinceMinigameStart; // 0 if no active minigame
    public string scene; // unity scene name for explicit attribution
    public string area;
    public string outcome;
    public string reason;
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
}

[Serializable]
public class KeyEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public string scene; // unity scene name for explicit attribution
    public string type = "input";     // constant: "input"
    public string device = "keyboard"; // constant: "keyboard"
    public string action;        // "down" | "up" | "repeat"
    public string key;           // e.g., "Space", "A", "LeftArrow"
    public float heldMs;         // duration in ms for "up" events; 0 for "down"
    public bool isRepeat;        // true if this event was generated by key-repeat
    public Vector2 playerPos;    // player world position (excluded in dwarf/memory scenes)
}

[Serializable]
public class SceneEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public string scene; // unity scene name for explicit attribution
    public string eventType; // scene_enter | scene_exit
    public string sceneVisitId; // GUID for a single continuous visit to a scene
    public string fromScene; // optional, previous scene name (grouped)
    public string toScene;   // optional, next/current scene name (grouped)
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
}

[Serializable]
public class MiniGameEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public float timeSinceMinigameStart; // 0 at minigame start
    public string scene; // unity scene name for explicit attribution
    public string eventType; // start/end/paused/resumed/custom
    public string reason;    // optional info (e.g., why ended)
}

[Serializable]
public class MemoryClickEvent
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public float timeSinceMinigameStart;
    public string scene; // unity scene name for explicit attribution
    public int level;
    public string result;   // "right" | "wrong"
    public int livesLeft;   // memory game only
}

[Serializable]
public class MemoryLevelResult
{
    public string time;
    public float timeSinceStart;
    public float timeSinceSceneStart;
    public float timeSinceMinigameStart;
    public string scene; // unity scene name for explicit attribution
    public int level;
    public string result;   // "win" | "fail"
    public string reason;   // optional context
    public int livesLeft;   // memory game only
}

[Serializable]
public class MinigameSection
{
    public string name; // minigame name, e.g., "memory"
    public List<MiniGameEvent> events = new List<MiniGameEvent>();
    public List<OutcomeEvent> outcomes = new List<OutcomeEvent>();
    public List<MemoryClickEvent> clicks = new List<MemoryClickEvent>();
    public List<MemoryLevelResult> levelResults = new List<MemoryLevelResult>();
    // Dwarf memory game: mouse inputs during the minigame
    public List<MouseInputEvent> mouseInputs = new List<MouseInputEvent>();
    // Summary result (to avoid ambiguity when reading per-level items)
    public string finalResult;   // "win" | "fail" | null
    public string finalReason;   // e.g., "game_over" | "all_levels_cleared"
    public string finishedTime;  // ISO timestamp when ended
    public float finishedSinceStart;
    public float finishedSinceSceneStart;
    public float finishedSinceMinigameStart;
    // Trial-level logging containers
    public List<ForestItemSpawnEvent> forestItemSpawns = new List<ForestItemSpawnEvent>();
    public List<ForestItemResolveEvent> forestItemResolves = new List<ForestItemResolveEvent>();
    public List<RiverJumpStartEvent> riverJumpStarts = new List<RiverJumpStartEvent>();
    public List<RiverJumpLandEvent> riverJumpLands = new List<RiverJumpLandEvent>();
    public List<RiverCollisionEvent> riverCollisions = new List<RiverCollisionEvent>();
    public List<RiverFinishEvent> riverFinish = new List<RiverFinishEvent>();
    // Dwarf memory game: trial stimulus/response logs per level
    public List<DwarfTrialStartEvent> dwarfTrialStarts = new List<DwarfTrialStartEvent>();
    public List<DwarfTrialResponseEvent> dwarfTrialResponses = new List<DwarfTrialResponseEvent>();
}

[Serializable]
public class MouseInputEvent
{
    public string type = "mouse_input";
    public string time;
    public string scene; // unity scene name for explicit attribution
    public string sceneVisitId;
    public string minigameRunId;
    public string button; // "left" | "right"
    public string action; // "down" | "up"
    public Vector2 screenPos;
    public Vector2 worldPos;
    public float tScene; // time since scene visit start
    public float tMini;  // time since minigame start
}

[Serializable]
public class ForestItemSpawnEvent
{
    public string type = "forest_item_spawn";
    public string scene; // unity scene name for explicit attribution
    public string sceneVisitId;
    public string minigameRunId;
    public string itemId;
    public string itemType; // "screw" | "blueberry"
    public Vector2 spawnPos;
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
    public float tScene;
    public float tMini;
}

[Serializable]
public class ForestItemResolveEvent
{
    public string type = "forest_item_resolve";
    public string scene; // unity scene name for explicit attribution
    public string sceneVisitId;
    public string minigameRunId;
    public string itemId;
    public string itemType; // "screw" | "blueberry"
    public string resolution; // "collected" | "missed" | "expired"
    public string collector;  // e.g., "player"
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
    public float tScene;
    public float tMini;
}

[Serializable]
public class RiverJumpStartEvent
{
    public string type = "river_jump_start";
    public string scene; // unity scene name for explicit attribution
    public string jumpId; // unique per jump
    public string fromRockId;
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
    public float tMini;
}

[Serializable]
public class RiverJumpLandEvent
{
    public string type = "river_jump_land";
    public string scene; // unity scene name for explicit attribution
    public string jumpId; // match start
    public string toRockId;
    public bool success;
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
    public float tMini;
}

[Serializable]
public class RiverCollisionEvent
{
    public string type = "river_collision";
    public string scene; // unity scene name for explicit attribution
    public string with; // "piranha" | "water"
    public Vector2 pos;
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
}

[Serializable]
public class RiverFinishEvent
{
    public string type = "river_finish";
    public string scene; // unity scene name for explicit attribution
    public string result; // "win" | "lose"
    public Vector2 playerPos; // player world position (excluded in dwarf/memory scenes)
    public string time;
}

[Serializable]
public class ProximityApproachEvent
{
    public string type = "approach_target"; // player moved towards a nearby target
    public string scene; // area/scene label (e.g., "forest" | "river")
    public string targetType; // "fish" | "blueberry"
    public string targetId;   // name or unique id
    public Vector2 targetPos; // world position of target at time of log
    public Vector2 playerPos; // player world position
    public float distance;    // current distance to target (world units)
    public float threshold;   // proximity threshold used (world units)
    public string time;       // ISO timestamp
    public float timeSinceStart;
    public float timeSinceSceneStart;
}

[Serializable]
public class DwarfTrialStartEvent
{
    public string type = "dwarf_trial_start";
    public string scene; // unity scene name for explicit attribution
    public string minigameRunId;
    public int level;
    public List<string> shownItems; // e.g., ["apple","key","hat"]
    public string correctItem;      // e.g., "key"
    public string time;             // ISO timestamp
}

[Serializable]
public class DwarfTrialResponseEvent
{
    public string type = "dwarf_trial_response";
    public string scene; // unity scene name for explicit attribution
    public int level;
    public string selectedItem;
    public bool isCorrect;
    public int reactionTimeMs;
    public string time;             // ISO timestamp
}

[Serializable]
public class SceneSection
{
    public string scene; // scene name (e.g., "start", "river", "forest", "dwarf")
    public List<SceneEvent> events = new List<SceneEvent>();
    public List<KeyEvent> keys = new List<KeyEvent>();
    public List<OutcomeEvent> outcomes = new List<OutcomeEvent>();
    public List<MinigameSection> minigames = new List<MinigameSection>();
    // River is not a minigame: store river trial logs directly under the scene section
    public List<RiverJumpStartEvent> riverJumpStarts = new List<RiverJumpStartEvent>();
    public List<RiverJumpLandEvent> riverJumpLands = new List<RiverJumpLandEvent>();
    public List<RiverCollisionEvent> riverCollisions = new List<RiverCollisionEvent>();
    public List<RiverFinishEvent> riverFinish = new List<RiverFinishEvent>();
    // Fish spawns (timestamp when a fish becomes active/seen in the scene)
    public List<FishSpawnEvent> fishSpawns = new List<FishSpawnEvent>();
    // Proximity/approach logs (player moving towards a nearby fish/blueberry)
    public List<ProximityApproachEvent> approaches = new List<ProximityApproachEvent>();
}

[Serializable]
public class SessionData
{
    public string sessionId;
    public string playerName;
    public string startTime;
    public string endTime;
    // New per-scene hierarchy
    public List<SceneSection> scenes = new List<SceneSection>();
    // Scene transitions/events (loaded/unloaded) kept separately
    public List<SceneEvent> sceneEvents = new List<SceneEvent>();
}

[Serializable]
public class FishSpawnEvent
{
    public string type = "fish_spawn";
    public string scene; // area/scene label (e.g., "river" | "forest")
    public string fishId;
    public Vector2 fishPos;
    public string time; // ISO timestamp
    public float tScene; // time since scene visit start
}
